#########################################################################
# ⭐⭐⭐  Set parameters carefully for satisfied performance!   ⭐⭐⭐ #
#########################################################################

PLOT:
    CL: true  # 是否绘图,只能绘制一个
    CD: false
    Cl: false
    Cm: false
    Cn: false
    